2019-08-19 16:52:04,467 file.manager INFO 1.2.0
2019-08-19 16:52:04,467 file.manager INFO Copyright (C) 2003-2010
2019-08-19 16:52:04,467 file.manager INFO   Noriaki Ando
2019-08-19 16:52:04,467 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-08-19 16:52:04,467 file.manager INFO Manager starting.
2019-08-19 16:52:04,469 file.manager INFO Starting local logging.
2019-08-19 16:52:04,473 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-08-19 16:52:06,483 file.ManagerServant INFO Master manager not found
2019-08-19 16:52:06,483 file.LocalServiceAdmin INFO All the local services are enabled.
2019-08-19 16:52:06,490 file.manager INFO Component type conf file: RSNPUnitConnector.conf loaded.
2019-08-19 16:52:06,496 file.ec_base INFO setRate(1000000.000000) done
2019-08-19 16:52:06,496 file.ec_base INFO setRate(1000.000000) done
2019-08-19 16:52:06,497 file.rtobject INFO 1 execution context was created.
2019-08-19 16:52:06,500 file.rtobject INFO Initial active configuration set is default.
2019-08-19 16:52:08,894 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-08-19 16:52:08,894 file.SdoServiceAdmin ERROR type  already exists.
2019-08-19 16:52:18,546 file.ManagerServant INFO Master manager not found
2019-08-19 16:52:30,621 file.ManagerServant INFO Master manager not found
2019-08-19 16:52:42,691 file.ManagerServant INFO Master manager not found
2019-08-19 16:52:53,855 file.ec_base WARNING The component is not responding.
2019-08-19 16:52:53,855 file.ec_base ERROR Unknown error: Invalid state transition.
2019-08-19 16:52:54,408 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。

2019-08-19 16:52:54,776 file.ManagerServant INFO Master manager not found
2019-08-19 16:53:06,871 file.ManagerServant INFO Master manager not found
2019-08-19 16:53:18,937 file.ManagerServant INFO Master manager not found
2019-08-19 16:53:31,009 file.ManagerServant INFO Master manager not found
2019-08-19 16:53:43,088 file.ManagerServant INFO Master manager not found
2019-08-19 16:53:55,157 file.ManagerServant INFO Master manager not found
2019-08-19 16:54:07,226 file.ManagerServant INFO Master manager not found
2019-08-19 16:54:19,296 file.ManagerServant INFO Master manager not found
2019-08-19 16:54:31,365 file.ManagerServant INFO Master manager not found
2019-08-19 16:54:43,433 file.ManagerServant INFO Master manager not found
2019-08-19 16:54:55,506 file.ManagerServant INFO Master manager not found
2019-08-19 16:55:07,588 file.ManagerServant INFO Master manager not found
2019-08-19 16:55:19,665 file.ManagerServant INFO Master manager not found
2019-08-19 16:55:31,743 file.ManagerServant INFO Master manager not found
2019-08-19 16:55:43,821 file.ManagerServant INFO Master manager not found
2019-08-19 16:55:55,918 file.ManagerServant INFO Master manager not found
2019-08-19 16:56:08,002 file.ManagerServant INFO Master manager not found
2019-08-19 16:56:20,072 file.ManagerServant INFO Master manager not found
2019-08-19 16:56:32,151 file.ManagerServant INFO Master manager not found
2019-08-19 16:56:44,237 file.ManagerServant INFO Master manager not found
2019-08-19 16:56:56,420 file.ManagerServant INFO Master manager not found
2019-08-19 16:57:08,638 file.ManagerServant INFO Master manager not found
2019-08-19 16:57:20,697 file.ManagerServant INFO Master manager not found
2019-08-19 16:57:32,773 file.ManagerServant INFO Master manager not found
2019-08-19 16:57:44,846 file.ManagerServant INFO Master manager not found
2019-08-19 16:57:56,951 file.ManagerServant INFO Master manager not found
2019-08-19 16:58:09,042 file.ManagerServant INFO Master manager not found
2019-08-19 16:58:21,111 file.ManagerServant INFO Master manager not found
2019-08-19 16:58:33,177 file.ManagerServant INFO Master manager not found
2019-08-19 16:58:45,240 file.ManagerServant INFO Master manager not found
2019-08-19 16:58:57,318 file.ManagerServant INFO Master manager not found
2019-08-19 16:59:09,392 file.ManagerServant INFO Master manager not found
2019-08-19 16:59:21,461 file.ManagerServant INFO Master manager not found
2019-08-19 16:59:33,525 file.ManagerServant INFO Master manager not found
2019-08-19 16:59:45,599 file.ManagerServant INFO Master manager not found
2019-08-19 16:59:57,681 file.ManagerServant INFO Master manager not found
2019-08-19 17:00:09,769 file.ManagerServant INFO Master manager not found
2019-08-19 17:00:21,845 file.ManagerServant INFO Master manager not found
2019-08-19 17:00:33,915 file.ManagerServant INFO Master manager not found
2019-08-19 17:00:45,986 file.ManagerServant INFO Master manager not found
2019-08-19 17:00:58,055 file.ManagerServant INFO Master manager not found
2019-08-19 17:01:10,118 file.ManagerServant INFO Master manager not found
2019-08-19 17:01:22,184 file.ManagerServant INFO Master manager not found
2019-08-19 17:01:34,266 file.ManagerServant INFO Master manager not found
2019-08-19 17:01:46,344 file.ManagerServant INFO Master manager not found
2019-08-19 17:01:58,418 file.ManagerServant INFO Master manager not found
2019-08-19 17:02:10,483 file.ManagerServant INFO Master manager not found
2019-08-19 17:02:22,546 file.ManagerServant INFO Master manager not found
2019-08-19 17:02:34,614 file.ManagerServant INFO Master manager not found
2019-08-19 17:02:46,696 file.ManagerServant INFO Master manager not found
2019-08-19 17:02:58,766 file.ManagerServant INFO Master manager not found
2019-08-19 17:03:02,473 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:03:06,394 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-08-19 17:03:10,868 file.ManagerServant INFO Master manager not found
2019-08-19 17:03:15,617 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:03:22,971 file.ManagerServant INFO Master manager not found
2019-08-19 17:03:35,104 file.ManagerServant INFO Master manager not found
2019-08-19 17:03:47,213 file.ManagerServant INFO Master manager not found
2019-08-19 17:03:59,329 file.ManagerServant INFO Master manager not found
2019-08-19 17:04:11,434 file.ManagerServant INFO Master manager not found
2019-08-19 17:04:23,549 file.ManagerServant INFO Master manager not found
2019-08-19 17:04:35,650 file.ManagerServant INFO Master manager not found
2019-08-19 17:04:47,775 file.ManagerServant INFO Master manager not found
2019-08-19 17:04:59,895 file.ManagerServant INFO Master manager not found
2019-08-19 17:05:12,003 file.ManagerServant INFO Master manager not found
2019-08-19 17:05:24,105 file.ManagerServant INFO Master manager not found
2019-08-19 17:05:36,184 file.ManagerServant INFO Master manager not found
2019-08-19 17:05:40,598 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:05:48,276 file.ManagerServant INFO Master manager not found
2019-08-19 17:06:00,342 file.ManagerServant INFO Master manager not found
2019-08-19 17:06:12,417 file.ManagerServant INFO Master manager not found
2019-08-19 17:06:24,480 file.ManagerServant INFO Master manager not found
2019-08-19 17:06:36,551 file.ManagerServant INFO Master manager not found
2019-08-19 17:06:48,631 file.ManagerServant INFO Master manager not found
2019-08-19 17:07:00,713 file.ManagerServant INFO Master manager not found
2019-08-19 17:07:12,796 file.ManagerServant INFO Master manager not found
2019-08-19 17:07:24,882 file.ManagerServant INFO Master manager not found
2019-08-19 17:07:36,957 file.ManagerServant INFO Master manager not found
2019-08-19 17:07:49,029 file.ManagerServant INFO Master manager not found
2019-08-19 17:08:01,125 file.ManagerServant INFO Master manager not found
2019-08-19 17:08:13,191 file.ManagerServant INFO Master manager not found
2019-08-19 17:08:25,273 file.ManagerServant INFO Master manager not found
2019-08-19 17:08:33,056 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:08:37,362 file.ManagerServant INFO Master manager not found
2019-08-19 17:08:49,464 file.ManagerServant INFO Master manager not found
2019-08-19 17:09:01,568 file.ManagerServant INFO Master manager not found
2019-08-19 17:09:13,658 file.ManagerServant INFO Master manager not found
2019-08-19 17:09:25,724 file.ManagerServant INFO Master manager not found
2019-08-19 17:09:37,796 file.ManagerServant INFO Master manager not found
2019-08-19 17:09:49,880 file.ManagerServant INFO Master manager not found
2019-08-19 17:10:01,957 file.ManagerServant INFO Master manager not found
2019-08-19 17:10:14,032 file.ManagerServant INFO Master manager not found
2019-08-19 17:10:26,117 file.ManagerServant INFO Master manager not found
2019-08-19 17:10:38,186 file.ManagerServant INFO Master manager not found
2019-08-19 17:10:50,239 file.ManagerServant INFO Master manager not found
2019-08-19 17:11:02,311 file.ManagerServant INFO Master manager not found
2019-08-19 17:11:14,381 file.ManagerServant INFO Master manager not found
2019-08-19 17:11:26,444 file.ManagerServant INFO Master manager not found
2019-08-19 17:11:38,513 file.ManagerServant INFO Master manager not found
2019-08-19 17:11:50,575 file.ManagerServant INFO Master manager not found
2019-08-19 17:12:02,648 file.ManagerServant INFO Master manager not found
2019-08-19 17:12:14,723 file.ManagerServant INFO Master manager not found
2019-08-19 17:12:26,805 file.ManagerServant INFO Master manager not found
2019-08-19 17:12:38,882 file.ManagerServant INFO Master manager not found
2019-08-19 17:12:50,953 file.ManagerServant INFO Master manager not found
2019-08-19 17:13:03,040 file.ManagerServant INFO Master manager not found
2019-08-19 17:13:15,119 file.ManagerServant INFO Master manager not found
2019-08-19 17:13:27,194 file.ManagerServant INFO Master manager not found
2019-08-19 17:13:39,283 file.ManagerServant INFO Master manager not found
2019-08-19 17:13:51,364 file.ManagerServant INFO Master manager not found
2019-08-19 17:14:03,424 file.ManagerServant INFO Master manager not found
2019-08-19 17:14:15,479 file.ManagerServant INFO Master manager not found
2019-08-19 17:14:27,548 file.ManagerServant INFO Master manager not found
2019-08-19 17:14:39,614 file.ManagerServant INFO Master manager not found
2019-08-19 17:14:51,673 file.ManagerServant INFO Master manager not found
2019-08-19 17:15:03,759 file.ManagerServant INFO Master manager not found
2019-08-19 17:15:15,842 file.ManagerServant INFO Master manager not found
2019-08-19 17:15:27,904 file.ManagerServant INFO Master manager not found
2019-08-19 17:15:39,976 file.ManagerServant INFO Master manager not found
2019-08-19 17:15:52,042 file.ManagerServant INFO Master manager not found
2019-08-19 17:16:04,115 file.ManagerServant INFO Master manager not found
2019-08-19 17:16:14,233 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:16:16,180 file.ManagerServant INFO Master manager not found
2019-08-19 17:16:28,255 file.ManagerServant INFO Master manager not found
2019-08-19 17:16:40,348 file.ManagerServant INFO Master manager not found
2019-08-19 17:16:52,417 file.ManagerServant INFO Master manager not found
2019-08-19 17:17:04,487 file.ManagerServant INFO Master manager not found
2019-08-19 17:17:16,556 file.ManagerServant INFO Master manager not found
2019-08-19 17:17:28,618 file.ManagerServant INFO Master manager not found
2019-08-19 17:17:40,687 file.ManagerServant INFO Master manager not found
2019-08-19 17:17:46,417 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:17:52,782 file.ManagerServant INFO Master manager not found
2019-08-19 17:18:04,842 file.ManagerServant INFO Master manager not found
2019-08-19 17:18:16,911 file.ManagerServant INFO Master manager not found
2019-08-19 17:18:28,976 file.ManagerServant INFO Master manager not found
2019-08-19 17:18:41,052 file.ManagerServant INFO Master manager not found
2019-08-19 17:18:53,130 file.ManagerServant INFO Master manager not found
2019-08-19 17:19:04,513 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:19:05,207 file.ManagerServant INFO Master manager not found
2019-08-19 17:19:17,316 file.ManagerServant INFO Master manager not found
2019-08-19 17:19:24,482 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 17:19:29,411 file.ManagerServant INFO Master manager not found
2019-08-19 17:19:41,486 file.ManagerServant INFO Master manager not found
2019-08-19 17:19:53,591 file.ManagerServant INFO Master manager not found
2019-08-19 17:20:05,670 file.ManagerServant INFO Master manager not found
2019-08-19 17:20:17,744 file.ManagerServant INFO Master manager not found
2019-08-19 17:20:29,828 file.ManagerServant INFO Master manager not found
2019-08-19 17:20:41,892 file.ManagerServant INFO Master manager not found
2019-08-19 17:20:53,979 file.ManagerServant INFO Master manager not found
2019-08-19 17:21:06,049 file.ManagerServant INFO Master manager not found
2019-08-19 17:21:18,137 file.ManagerServant INFO Master manager not found
2019-08-19 17:21:30,214 file.ManagerServant INFO Master manager not found
2019-08-19 17:21:42,292 file.ManagerServant INFO Master manager not found
2019-08-19 17:21:54,352 file.ManagerServant INFO Master manager not found
2019-08-19 17:22:06,424 file.ManagerServant INFO Master manager not found
2019-08-19 17:22:18,519 file.ManagerServant INFO Master manager not found
2019-08-19 17:22:30,595 file.ManagerServant INFO Master manager not found
2019-08-19 17:22:42,657 file.ManagerServant INFO Master manager not found
2019-08-19 17:22:54,721 file.ManagerServant INFO Master manager not found
2019-08-19 17:23:06,792 file.ManagerServant INFO Master manager not found
2019-08-19 17:23:18,865 file.ManagerServant INFO Master manager not found
2019-08-19 17:23:30,937 file.ManagerServant INFO Master manager not found
2019-08-19 17:23:42,996 file.ManagerServant INFO Master manager not found
2019-08-19 17:23:55,078 file.ManagerServant INFO Master manager not found
2019-08-19 17:24:07,150 file.ManagerServant INFO Master manager not found
2019-08-19 17:24:10,480 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-08-19 17:24:10,483 file.ec_worker WARNING ExecutionContext is already stopped.
2019-08-19 17:24:10,483 file.ec_base ERROR Invoking on_shutdown() for each RTC failed.
