2019-08-20 20:49:49,463 file.manager INFO 1.2.0
2019-08-20 20:49:49,463 file.manager INFO Copyright (C) 2003-2010
2019-08-20 20:49:49,463 file.manager INFO   Noriaki Ando
2019-08-20 20:49:49,463 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-08-20 20:49:49,463 file.manager INFO Manager starting.
2019-08-20 20:49:49,463 file.manager INFO Starting local logging.
2019-08-20 20:49:49,469 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-08-20 20:49:51,479 file.ManagerServant INFO Master manager not found
2019-08-20 20:49:51,480 file.LocalServiceAdmin INFO All the local services are enabled.
2019-08-20 20:49:51,486 file.manager INFO Component type conf file: RSNPUnitConnector.conf loaded.
2019-08-20 20:49:51,494 file.ec_base INFO setRate(1000000.000000) done
2019-08-20 20:49:51,494 file.ec_base INFO setRate(1000.000000) done
2019-08-20 20:49:51,496 file.rtobject INFO 1 execution context was created.
2019-08-20 20:49:51,497 file.rtobject INFO Initial active configuration set is default.
2019-08-20 20:49:53,006 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-08-20 20:49:53,006 file.SdoServiceAdmin ERROR type  already exists.
2019-08-20 20:49:59,167 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 149, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
AttributeError: 'RSNPUnitConnector' object has no attribute '_Port'

2019-08-20 20:50:03,490 file.ManagerServant INFO Master manager not found
2019-08-20 20:50:15,586 file.ManagerServant INFO Master manager not found
2019-08-20 20:50:15,867 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 156, in onActivated
    self._Serial.open()
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM10': WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')

2019-08-20 20:50:27,681 file.ManagerServant INFO Master manager not found
2019-08-20 20:50:39,769 file.ManagerServant INFO Master manager not found
2019-08-20 20:50:42,361 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-08-20 20:50:42,365 file.ec_worker WARNING ExecutionContext is already stopped.
2019-08-20 20:50:42,365 file.ec_base ERROR Invoking on_shutdown() for each RTC failed.
